version: "3.8"

services:
  code-runner:
    image: code-runner
    build: .
    restart: unless-stopped
    volumes:
      - ./config.json:/etc/code-runner/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"